# Generated by Django 4.2.16 on 2026-10-02 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('change_description', models.TextField()),
                ('enhanced_spec', models.TextField(blank=True)),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('blast_radius', models.IntegerField(default=0)),
                ('confidence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ci_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('compare_branch', models.CharField(default='', max_length=255)),
                ('language', models.CharField(default='', max_length=100)),
                ('framework', models.CharField(default='', max_length=100)),
                ('stat_files', models.IntegerField(default=0)),
                ('stat_functions', models.IntegerField(default=0)),
                ('stat_apis', models.IntegerField(default=0)),
                ('stat_db_models', models.IntegerField(default=0)),
                ('stat_dependencies', models.IntegerField(default=0)),
                ('stat_env_vars', models.IntegerField(default=0)),
                ('stat_tests', models.IntegerField(default=0)),
                ('stat_security_findings', models.IntegerField(default=0)),
                ('health_project', models.IntegerField(default=0)),
                ('health_security', models.IntegerField(default=0)),
                ('health_dependencies', models.IntegerField(default=0)),
                ('health_maintainability', models.IntegerField(default=0)),
                ('health_configuration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ci_projects',
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('area', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'ci_security_findings',
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('file', 'File'), ('function', 'Function'), ('class', 'Class'), ('api', 'API'), ('database', 'Database'), ('service', 'Service'), ('dependency', 'Dependency'), ('env', 'Env Variable'), ('test', 'Test'), ('external', 'External'), ('user', 'User')], max_length=20)),
                ('tech', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('impact', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified'), ('affected', 'Affected'), ('unchanged', 'Unchanged')], max_length=12)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('why', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.changeanalysis')),
            ],
            options={
                'db_table': 'ci_graph_nodes',
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('impact', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('indirect', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified')], max_length=12)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.changeanalysis')),
            ],
            options={
                'db_table': 'ci_graph_edges',
            },
        ),
        migrations.CreateModel(
            name='EnvVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('used_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('set', 'Set'), ('missing', 'Missing')], default='set', max_length=10)),
                ('rotated', models.CharField(blank=True, max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'ci_env_variables',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Update Recommended', 'Update Recommended'), ('Security Risk', 'Security Risk'), ('Review', 'Review')], default='Healthy', max_length=30)),
                ('used_by', models.IntegerField(default=0)),
                ('license', models.CharField(blank=True, max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'ci_dependencies',
            },
        ),
        migrations.AddField(
            model_name='changeanalysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
